// apps/vue-web/src/app/error-handling/AppErrorBoundary.vue
<script setup lang="ts">
import { onErrorCaptured, shallowRef } from "vue";

import AppErrorFallback from "./AppErrorFallback.vue";
import { errorReporter } from "./error-reporter";

// 只保存是否发生异常，具体错误信息交给 reporter，不进入响应式状态。
const hasError = shallowRef(false);

// 捕获当前插槽组件树中的渲染和生命周期异常。
onErrorCaptured((error, _instance, info) => {
  // 先切换到恢复页面，避免故障组件继续参与后续渲染。
  hasError.value = true;
  errorReporter.report({
    error,
    source: "vue-render",
    context: {
      componentInfo: info,
      route: window.location.pathname,
    },
  });

  // 返回 false 阻止同一错误继续向上传播，避免重复上报。
  return false;
});

// 当前模板采用整页刷新恢复，后续也可替换为重新初始化局部模块。
function reloadApplication() {
  window.location.reload();
}
</script>

<template>
  <!-- 异常时展示稳定恢复页，正常时透明渲染原插槽内容。 -->
  <AppErrorFallback v-if="hasError" @reload="reloadApplication" />
  <slot v-else />
</template>

// templates/apps/react/src/app/error-handling/AppErrorBoundary.tsx
import { Component, type ErrorInfo, type ReactNode } from "react";

import { AppErrorFallback } from "./AppErrorFallback";
import { errorReporter } from "./error-reporter";
import "./app-error.scss";

// children 是异常边界保护的整个应用组件树。
interface AppErrorBoundaryProps {
  children: ReactNode;
}

// React 类组件异常边界通过 state 决定是否切换到恢复页面。
interface AppErrorBoundaryState {
  hasError: boolean;
}

// React 目前要求使用类组件实现渲染阶段 Error Boundary。
export class AppErrorBoundary extends Component<
  AppErrorBoundaryProps,
  AppErrorBoundaryState
> {
  state: AppErrorBoundaryState = {
    hasError: false,
  };

  // 捕获异常后立即切换 UI，避免用户看到空白页面。
  static getDerivedStateFromError(): AppErrorBoundaryState {
    return { hasError: true };
  }

  // componentDidCatch 提供组件栈，适合补充监控上下文。
  componentDidCatch(error: Error, info: ErrorInfo) {
    errorReporter.report({
      error,
      source: "react-render",
      context: {
        componentStack: info.componentStack,
        route: window.location.pathname,
      },
    });
  }

  render() {
    // 异常发生后只显示稳定的恢复页，不向用户暴露错误堆栈。
    if (this.state.hasError) {
      return <AppErrorFallback onReload={() => window.location.reload()} />;
    }

    // 正常状态下透明渲染原应用，不改变业务组件层级。
    return this.props.children;
  }
}
